#!/usr/bin/env ansible-playbook -i hosts
---

- name: Ansible Playbook for configuring Pi-Hole on Raspberry Pi
  hosts: servers
  roles:
    - pi
  remote_user: {{ ansible_ssh_user }}
  become: true
  gather_facts: yes
